steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/alamanda-394003/posyandu-alamanda', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/alamanda-394003/posyandu-alamanda']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'posyandu-alamanda'
      - '--image=gcr.io/alamanda-394003/posyandu-alamanda'
      - '--platform=managed'
      - '--region=us-central1'
