steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/posyandu-alamanda:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/posyandu-alamanda:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'posyandu-alamanda'
      - '--image'
      - 'gcr.io/$PROJECT_ID/posyandu-alamanda:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
    images:
      - 'gcr.io/$PROJECT_ID/posyandu-alamanda:$COMMIT_SHA'
